version: '3'

services:
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: passanalysis
            MYSQL_USER: passanalysis
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password 
        volumes:
            - ./schema:/docker-entrypoint-initdb.d
        networks:
            - default
